FROM python:3.9-slim as builder
RUN pip3 install ansible==3.1.0 ansible-lint

FROM python:3.9-slim
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages
COPY --from=builder /usr/local/bin/ansible /usr/local/bin
COPY --from=builder /usr/local/bin/ansible-* /usr/local/bin
